### ISSUE TITLE
Thank you lovyan03!

### ISSUE THREAD

**Issue by Sarah-C** [m5stack/M5GFX#11]
Your skills with embedded graphics are unmatched.
I was very impressed with the ESP32_ScreenShotReceiver you wrote - expertly avoiding the tight memory limits, and making an incredibly fast real-time windows/ESP32 combined image encoding/decoding system!

Then today I saw your M5GFX library with Jpg drawing! Amazing!

Sorry this isn't an "Issue" - GitHub doesn't have a "Praise" tab.

xx

**Comment by lovyan03** [comment]
Thank you for the compliment.
I'm sorry, but this repository is the official repository of M5Stack, so please direct your personal messages to [LovyanGFX repository](https://github.com/lovyan03/LovyanGFX) or [twitter](https://twitter.com/lovyan03).
