### ISSUE TITLE
How to use 16bit colors instead of 32 bit colors?

### ISSUE THREAD

**Issue by Fischkopppp** [m5stack/M5GFX#31]
Hi Lovyan03,

I am using M5 ATOM Display and I want to use 16bit RGB565 colors. 
I have used display.setColorDepth(16); in the setup after display.init();
However the 16bit colors (for example: 0xCFFC) are interpreted as 32bit colors (0x00CFFC).

**Comment by lovyan03** [comment]
@Fischkopppp 
Use type int or uint16_t. If you do so, it will be interpreted as RGB565.
If use type uint32_t, it will be interpreted as RGB888.
This behavior is not affected by the setColorDepth status.
