### ISSUE TITLE
Arduino package 2.0.0 build error: 'class TwoWire' has no member named 'end'

### ISSUE THREAD

**Issue by tobozo** [m5stack/M5GFX#33]
Hi, and thanks for the awesome library !

```log
~/Arduino/libraries/M5GFX/src/lgfx/v1/platforms/esp32/common.cpp:741:16: 
  error: 'class TwoWire' has no member named 'end'; did you mean 'read'?
       twowire->end();
                ^~~
                read
```

**Comment by lovyan03** [comment]
@tobozo 
Thanks for the report.
It is a LovyanGFX bug and I will address it as soon as I can fix it there.

**Comment by lovyan03** [comment]
@tobozo 
Bug fixes were made in the develop branch.

https://github.com/m5stack/M5GFX/commit/0453041b6f4a122378a0d873af3385586be4fb7e

**Comment by tobozo** [comment]
thanks I can confirm the compilation error is gone when using the develop branch
