### ISSUE TITLE
esp32c3 supported?

### ISSUE THREAD

**Issue by kangz543g** [m5stack/M5GFX#77]
How to use M5GFX on GC9A01 on ESP32C3?
Thank you.

**Comment by lovyan03** [comment]
Hello, @kangz543g 
M5GFX supports ESP32C3, but does not support anything other than M5Stack products. How do you want to use GC9A01?

**Comment by kangz543g** [comment]
![사진_사진_20240218_2](https://github.com/m5stack/M5GFX/assets/79963672/329f6e31-d2b1-4985-91cb-77efa915a1d3)
![사진_사진_20240218_3](https://github.com/m5stack/M5GFX/assets/79963672/c3ae9d44-f62f-4186-9b9a-cbc5631c36bc)
no M5GFX supports. success ESP32C3 use GC9A01.
![사진_사진_20240218_1](https://github.com/m5stack/M5GFX/assets/79963672/c8e83e2e-cef1-4972-bd10-92a9c4520007)

**Comment by lovyan03** [comment]
congratulations.
Is the problem solved?
