### ISSUE TITLE
Error: cannot declare variable 'file' to be of abstract type 'lgfx::v1::DataWrapperT<fs::SDFS>'

### ISSUE THREAD

**Issue by chillymattster** [m5stack/M5GFX#79]
Hi,
I'm quite new to M5Stack and own a CoreS3. Trying to compile with VS Code and Platformio, I get an error exactly as described here: [M5Stack Community: Cardputer and drawJpgFile](https://forum.m5stack.com/topic/6040/cardputer-and-drawjpgfile)

It looks like being related to [issue #72 Question: drawPngFile using SdFat](https://github.com/m5stack/M5GFX/issues/72)

Are there any ideas on how to solve this?
Any help is greatly appreciated!

**Comment by lovyan03** [comment]
Hello, @chillymattster 

If you want to use a set of functions to handle SD/SPIFFS/HTTP,
 please include <SD.h>,<SPIFFS.h>,<HTTPClient.h> before <M5GFX.h>


```cpp
#include <SD.h>  // before M5GFX isOK.
#include <M5GFX.h>
```

```cpp
#include <M5GFX.h>
#include <SD.h>  // after M5GFX. is NG
```

**Comment by chillymattster** [comment]
Hi @lovyan03,

that's an amazingly fast and very helpful answer, many thanks, very much appreciated! 😄 

I'm not directly referencing <M5GFX.h> but <M5CoreS3.h> so for me the solution is 
```C++
#include <SD.h>  
#include <M5CoreS3.h>
```

**Comment by PeterOFre** [comment]
Thank you very much chillymattster,
you helped me as well !

After switching from #include <M5Stack.h>
to #include "M5Unified.h"
I have entered the #include "SD.h"  
after the #include "M5Unified.h" which caused the error message mentioned above.

According to you the right order is:
#include "SD.h"  
 #include "M5Unified.h" 

Again: Thank you very much and best regards
Peter
